[terminal.shell]
program = "/usr/bin/fish"

[font]
normal = { family = "DejaVu Sans Mono", style = "Regular" }
bold = { family = "DejaVu Sans Mono", style = "Bold" }
italic = { family = "DejaVu Sans Mono", style = "Italic" }
size = 10

[terminal]

[window]
padding = { x = 10, y = 10 }
startup_mode = "SimpleFullscreen"

[bell]
animation = "EaseOutExpo"
duration = 10
color = "#f7768e"

[debug]
log_level = "Warn"  
render_timer = false

[colors]
[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'

[colors.normal]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'

# Bright Colors
# Bright Colors
[colors.bright]
black = '#5c6a72'
red = '#f85552'
green = '#8da101'
yellow = '#dfa000'
blue = '#3a94c5'
magenta = '#df69ba'
cyan = '#35a77c'
white = '#e0dcc7'

